=== bclipp/roadmap/materials.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="material">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="url" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="tag" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="lang" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:element name="materials">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="article" type="material"/>
                <xs:element name="course" type="material"/>
                <xs:element name="book" type="material"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== bclipp/roadmap/materials.xml
<?xml version="1.0" encoding="UTF-8"?>
<materials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="materials.xsd">
    <course lang="ru">
        <title>Разработка веб-сервисов на Go - основы языка</title>
        <url>https://www.coursera.org/learn/golang-webservices-1</url>
        <tags>
            <tag>go</tag>
        </tags>
    </course>

    <course lang="ru">
        <title>Разработка веб-сервисов на Golang, часть 2</title>
        <url>https://www.coursera.org/learn/golang-webservices-2</url>
        <tags>
            <tag>go</tag>
        </tags>
    </course>

    <article lang="en">
        <title>Effective Go</title>
        <url>https://golang.org/doc/effective_go.html</url>
        <tags>
            <tag>go</tag>
        </tags>
    </article>

    <article lang="en">
        <title>Go Slices: usage and internals</title>
        <url>https://blog.golang.org/go-slices-usage-and-internals</url>
        <tags>
            <tag>go_types_collections_slice</tag>
        </tags>
    </article>

    <article lang="en">
        <title>Manifesto for Agile Software Development</title>
        <url>https://agilemanifesto.org</url>
        <tags>
            <tag>management_paradigms_agile</tag>
        </tags>
    </article>

    <article lang="en">
        <title>The Twelve-Factor App</title>
        <url>https://12factor.net</url>
        <tags>
            <tag>development_methodologies_12factors</tag>
        </tags>
    </article>

    <article lang="en">
        <title>Commands</title>
        <url>https://golang.org/cmd/</url>
        <tags>
            <tag>go_tools</tag>
        </tags>
    </article>

    <article lang="en">
        <title>Go maps in action</title>
        <url>https://blog.golang.org/go-maps-in-action</url>
        <tags>
        <tag>go_types_collections_map</tag>
        </tags>
    </article>

    <article lang="en">
        <title>gofmt</title>
        <url>https://golang.org/cmd/gofmt/</url>
        <tags>
            <tag>go_tool_fmt</tag>
        </tags>
    </article>

    <article lang="en">
        <title>vet</title>
        <url>https://golang.org/cmd/vet/</url>
        <tags>
            <tag>go_tool_vet</tag>
        </tags>
    </article>

    <article lang="en">
        <title>Modules</title>
        <url>https://github.com/golang/go/wiki/Modules</url>
        <tags>
            <tag>go_tool_modules</tag>
        </tags>
    </article>

    <article lang="en">
        <title>NOSQL</title>
        <url>https://martinfowler.com/nosql.html</url>
        <tags>
            <tag>db_nosql</tag>
        </tags>
    </article>

    <book lang="en">
        <title>NoSQL Distilled</title>
        <url>https://martinfowler.com/books/nosql.html</url>
        <tags>
            <tag>db_nosql</tag>
        </tags>
    </book>
</materials>
